[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "2bRnXrf1JBDVXPbFm2NEYm22jnHrqvs8nS2RXBTrJcV3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/mort1b/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
